# Site settings
author: Natalia Edelson
title: Data Science Projects 
header-img: img/home-bg.png
email: nataliagoncharov@gmail.com
copyright_name: Natalia Edelson
description: > # this means to ignore newlines until "baseurl:"
  Using Python 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NataliaEde

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
